baseURL = ""
languageCode = "en-us"
title = "Hugo Blog by avash"
copyright = "All right reserved  @ AVASH JHA 2018 "
sectionPagesMenu = "main"
[taxonomies]
    tag="tags"
    category="categories"
    new = "news"
    tech = "techs"

